// app/layout.js
"use client";
import { useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/componenet/navbar";
import PopClicksCanvas from "@/componenet/PopClicksCanvas";
import SmoothScrollWrapper from "@/componenet/SmoothScrollWrapper";
import LetterPreloader from "@/componenet/preloader"; // ensure path matches
import SexyBackgroundWithBoxes from "@/componenet/background";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

// export const metadata = {
//   title: "Iftikhar — Portfolio",
//   description: "Iftikhar's portfolio",
// };

export default function RootLayout({ children }) {
  // true while preloader runs
  const [isLoading, setIsLoading] = useState(true);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${isLoading ? "overflow-hidden" : ""}`}
        style={{ minHeight: "100vh" }}
      >
        <PopClicksCanvas />
        {/* show preloader while loading */}
        {isLoading && (
          <LetterPreloader
            name="Iftikhar ali"
            total={2600}
            onFinish={() => {
              // slight delay lets fade finish nicely, then show app
              setTimeout(() => setIsLoading(false), 80);
            }}
          />
        )}

        {/* Components you wanted visible during loading */}
        <SexyBackgroundWithBoxes />

        {/* SmoothScrollWrapper is shown always; but Navbar & children appear only AFTER loading */}
        <SmoothScrollWrapper>
          {!isLoading && (
            <>
            {/* <div className="w-full flex items-center justify-center bg-pink-400 sticky left-1/2 top-5 z-50"> */}
              <Navbar />
            {/* </div> */}
              {/* main page content */}
              <div>{children}</div>
            </>
          )}
        </SmoothScrollWrapper>
      </body>
    </html>
  );
}




// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/componenet/navbar";
// import PopClicksCanvas from "@/componenet/PopClicksCanvas"
// import SmoothScrollWrapper from "@/componenet/SmoothScrollWrapper"
// import LetterPreloader from "@/componenet/preloader"
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// import SexyBackgroundWithBoxes from "@/componenet/background"
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable}
//         `}
//         // bg-gradient-royal text-white antialiased w-[100%] h-[100%] relative overflow-x-hidden
//       >
//         {/* <Preloader /> */}
//         <LetterPreloader name="Iftikhar" total={2600} />
//         <PopClicksCanvas />
//         <SexyBackgroundWithBoxes />
//         <SmoothScrollWrapper>

//         <Navbar />
//         <div className="fixed inset-0 w-[100%] h-[100%] z-[-1]">

//         </div>
//         {/* <div className="absolute inset-0  index-[-1] w-[100%] h-[100%]"></div> */}
//         <div className="">{children}</div>
//         </SmoothScrollWrapper>
//       </body>
//     </html>
//   );
// }
